### ISSUE TITLE
Player conditions not working properly

### ISSUE THREAD

**Issue by PolsatGraniePL** [FunnyGuilds/FunnySkAddon#32]
```
[10:40:54 INFO]: PolsatGraniePL issued server command: /sk reload ogolne
[10:40:54 ERROR]: #!#!
[10:40:54 ERROR]: #!#! [Skript] Severe Error:
[10:40:54 ERROR]: #!#!
[10:40:54 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[10:40:54 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[10:40:54 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[10:40:54 ERROR]: #!#!
[10:40:54 ERROR]: #!#! Stack trace:
[10:40:54 ERROR]: #!#! java.lang.NoClassDefFoundError: ch/njol/skript/lang/SkriptParser$ParseResult
[10:40:54 ERROR]: #!#!     at FunnySkAddon-2.2.13-Beta.jar//pl.funnyskaddon.skript.condition.PlayerCondition.init(PlayerCondition.kt:20)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.Condition.parse(Condition.java:77)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.Section.init(Section.java:71)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.Section.parse(Section.java:168)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1134)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:761)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$5(ScriptLoader.java:533)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:420)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:436)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:532)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1066)
[10:40:54 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
[10:40:54 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:40:54 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[10:40:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2316)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2127)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
[10:40:54 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[10:40:54 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[10:40:54 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:40:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[10:40:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[10:40:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404)
[10:40:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1382)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1293)
[10:40:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[10:40:54 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[10:40:54 ERROR]: #!#!
[10:40:54 ERROR]: #!#! Version Information:
[10:40:54 ERROR]: #!#!   Skript: 2.6 (OUTDATED)
[10:40:54 ERROR]: #!#!     Flavor: skriptlang-github
[10:40:54 ERROR]: #!#!     Date: 17:20:35.482878100
[10:40:54 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[10:40:54 ERROR]: #!#!   Minecraft: 1.17.1
[10:40:54 ERROR]: #!#!   Java: 17 (OpenJDK 64-Bit Server VM 17+35-2724)
[10:40:54 ERROR]: #!#!   OS: Linux amd64 3.10.0-1160.49.1.el7.x86_64
[10:40:54 ERROR]: #!#!
[10:40:54 ERROR]: #!#! Server platform: Paper
[10:40:54 ERROR]: #!#!
[10:40:54 ERROR]: #!#! Current node: null
[10:40:54 ERROR]: #!#! Current item: null
[10:40:54 ERROR]: #!#!
[10:40:54 ERROR]: #!#! Thread: Server thread
[10:40:54 ERROR]: #!#!
[10:40:54 ERROR]: #!#! Language: english
[10:40:54 ERROR]: #!#! Link parse mode: DISABLED
[10:40:54 ERROR]: #!#!
[10:40:54 ERROR]: #!#! End of Error.
[10:40:54 ERROR]: #!#!
```

przy 

```
on command:
	if player is in any guild region:
		cancel event
		send "Nie możesz używać komend na terenie gildi"
```

z drugą linijką jest tzw. nieskończony reload 
![image](https://user-images.githubusercontent.com/88681446/151141994-a396b9f7-ef1e-4fc8-8877-57536dfdad9f.png)
a bez niej już normalnie reloaduje
![image](https://user-images.githubusercontent.com/88681446/151142078-0d17b64c-e81c-4c15-8dd3-c4fd41a381ed.png)

![image](https://user-images.githubusercontent.com/88681446/151142195-416e9fc8-0e12-47ac-800e-26445d2d14f7.png)

**Comment by P3ridot** [comment]
Sprawdz [2.2.14-Beta](https://github.com/FunnyGuilds/FunnySkAddon/releases/tag/2.2.14-Beta)
