### ISSUE TITLE
Skript toString method return null

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#33]
```[19:54:11 ERROR]: #!#!
[19:54:11 ERROR]: #!#! [Skript] Severe Error:
[19:54:11 ERROR]: #!#! Could not load tablist.sk
[19:54:11 ERROR]: #!#!
[19:54:11 ERROR]: #!#! Something went horribly wrong with Skript.
[19:54:11 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[19:54:11 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[19:54:11 ERROR]: #!#! Here is full list of them:
[19:54:11 ERROR]: #!#! skLunar v1.0 skUtilities v0.9.2 (https://tim740.github.io/) skript-yaml v1.4 Tablisknu v1.0 (tlatoani.us/tablisknu) FunnySkAddon v2.2.13-Beta (funnyskaddon.pl) HolographicDisplaysAddon v1.0.0b
[19:54:11 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[19:54:11 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[19:54:11 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[19:54:11 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[19:54:11 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[19:54:11 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[19:54:11 ERROR]: #!#!
[19:54:11 ERROR]: #!#! Stack trace:
[19:54:11 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "expr" is null
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:295)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:131)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:521)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:800)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1302)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:61)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section.loadCode(Section.java:90)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section.loadOptionalCode(Section.java:145)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.sections.SecLoop.init(SecLoop.java:82)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:257)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section.loadCode(Section.java:90)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section.loadOptionalCode(Section.java:145)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.sections.SecLoop.init(SecLoop.java:82)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:257)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:46)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:138)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:721)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[19:54:11 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[19:54:11 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:54:11 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[19:54:11 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[19:54:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[19:54:11 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[19:54:11 ERROR]: #!#!
[19:54:11 ERROR]: #!#! Version Information:
[19:54:11 ERROR]: #!#!   Skript: 2.6.1 (latest)
[19:54:11 ERROR]: #!#!     Flavor: skriptlang-github
[19:54:11 ERROR]: #!#!     Date: 22:18:42.554713200
[19:54:11 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[19:54:11 ERROR]: #!#!   Minecraft: 1.16.5
[19:54:11 ERROR]: #!#!   Java: 16.0.2 (Java HotSpot(TM) 64-Bit Server VM 16.0.2+7-67)
[19:54:11 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[19:54:11 ERROR]: #!#!
[19:54:11 ERROR]: #!#! Server platform: Paper
[19:54:11 ERROR]: #!#!
[19:54:11 ERROR]: #!#! Current node: replace all "{G-TAG}" with "%{_gp}'s guild tag%" in {_slot} (tablist.sk, line 47)
[19:54:11 ERROR]: #!#! Current item: null
[19:54:11 ERROR]: #!#!
[19:54:11 ERROR]: #!#! Thread: Server thread
[19:54:11 ERROR]: #!#!
[19:54:11 ERROR]: #!#! Language: english
[19:54:11 ERROR]: #!#! Link parse mode: DISABLED
[19:54:11 ERROR]: #!#!
[19:54:11 ERROR]: #!#! End of Error.
[19:54:11 ERROR]: #!#!```

![image](https://user-images.githubusercontent.com/83598982/151228495-56233b11-c1f5-437f-99a4-caf0bdfaf434.png)
![image](https://user-images.githubusercontent.com/83598982/151228451-3fcda702-5d32-4922-8c5f-a9c551817823.png)

**Comment by pawelkuwa** [comment]
![image](https://user-images.githubusercontent.com/83598982/151241467-c129ed2a-d02f-4757-b722-2cb013627bd8.png)
jedno z rozwiązań

**Comment by pawelkuwa** [comment]
![image](https://user-images.githubusercontent.com/83598982/151366972-8f3fb3f9-16bd-46e0-a6aa-98a1e6c52adb.png)
również player top

**Comment by pawelkuwa** [comment]
![image](https://user-images.githubusercontent.com/83598982/151367370-ecaa871c-15d2-4c79-87a9-d91f82fe0807.png)
![image](https://user-images.githubusercontent.com/83598982/151367383-2992451e-b6ca-477f-a849-e44c649f959b.png)

**Comment by P3ridot** [comment]
Probably since 4afd942c3a395cf2c3e0b05883dbce9feedaefbf

**Comment by P3ridot** [comment]
Naprawione w [2.2.19-Beta](https://github.com/FunnyGuilds/FunnySkAddon/releases/tag/2.2.19-Beta)
