### ISSUE TITLE
Expressions patterns wrong form problem

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#35]
```[22:48:32 ERROR]: #!#!
[22:48:32 ERROR]: #!#! [Skript] Severe Error:
[22:48:32 ERROR]: #!#!
[22:48:32 ERROR]: #!#! Something went horribly wrong with Skript.
[22:48:32 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:48:32 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:48:32 ERROR]: #!#! Here is full list of them:
[22:48:32 ERROR]: #!#! skript-yaml v1.4 skUtilities v0.9.2 (https://tim740.github.io/) FunnySkAddon v2.2.17-Beta (funnyskaddon.pl) skript-db v1.3.3
[22:48:32 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:48:32 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:48:32 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:48:32 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:48:32 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:48:32 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:48:32 ERROR]: #!#!
[22:48:32 ERROR]: #!#! Stack trace:
[22:48:32 ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[22:48:32 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:272)
[22:48:32 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getSingle(UnparsedLiteral.java:302)
[22:48:32 ERROR]: #!#!     at pl.funnyskaddon.skript.EventExtensionKt.getGuild(EventExtension.kt:48)
[22:48:32 ERROR]: #!#!     at pl.funnyskaddon.skript.EventExtensionKt.getGuildOption(EventExtension.kt:52)
[22:48:32 ERROR]: #!#!     at pl.funnyskaddon.skript.expression.guild.GuildMembersExpression.get(GuildMembersExpression.kt:38)
[22:48:32 ERROR]: #!#!     at pl.funnyskaddon.skript.expression.guild.GuildMembersExpression.get(GuildMembersExpression.kt:17)
[22:48:32 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[22:48:32 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:273)
[22:48:32 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[22:48:32 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[22:48:32 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[22:48:32 ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[22:48:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:48:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485)
[22:48:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432)
[22:48:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[22:48:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[22:48:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[22:48:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[22:48:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[22:48:32 ERROR]: #!#!
[22:48:32 ERROR]: #!#! Version Information:
[22:48:32 ERROR]: #!#!   Skript: 2.6.1 (latest)
[22:48:32 ERROR]: #!#!     Flavor: skriptlang-github
[22:48:32 ERROR]: #!#!     Date: 22:18:42.554713200
[22:48:32 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[22:48:32 ERROR]: #!#!   Minecraft: 1.16.5
[22:48:32 ERROR]: #!#!   Java: 16.0.2 (Java HotSpot(TM) 64-Bit Server VM 16.0.2+7-67)
[22:48:32 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:48:32 ERROR]: #!#!
[22:48:32 ERROR]: #!#! Server platform: Paper
[22:48:32 ERROR]: #!#!
[22:48:32 ERROR]: #!#! Current node: null
[22:48:32 ERROR]: #!#! Current item: set {_list::*} (as java.lang.Object) to null
[22:48:32 ERROR]: #!#! Current trigger: function displayTest(simple event) (test.sk, line 14)
[22:48:32 ERROR]: #!#!
[22:48:32 ERROR]: #!#! Thread: Server thread
[22:48:32 ERROR]: #!#!
[22:48:32 ERROR]: #!#! Language: english
[22:48:32 ERROR]: #!#! Link parse mode: DISABLED
[22:48:32 ERROR]: #!#!
[22:48:32 ERROR]: #!#! End of Error.
[22:48:32 ERROR]: #!#!




- **[22:48:32 ERROR]: #!#! Current node: null
- [22:48:32 ERROR]: #!#! Current item: set {_list::*} (as java.lang.Object) to null
- [22:48:32 ERROR]: #!#! Current trigger: function displayTest(simple event) (test.sk, line 14)**```

**Comment by pawelkuwa** [comment]
![image](https://user-images.githubusercontent.com/83598982/152243339-ac1ca41d-fc96-4414-aaad-648e85befc7f.png)

**Comment by P3ridot** [comment]
GH-36

**Comment by P3ridot** [comment]
Następne błędy z tym `UnparsedLiterals must be converted before use` zgłaszaj w GH-33

**Comment by P3ridot** [comment]
Prawdopodobnie błąd występuje od 4afd942c3a395cf2c3e0b05883dbce9feedaefbf
