### ISSUE TITLE
Can't loop online players

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#36]
![image](https://user-images.githubusercontent.com/83598982/152272772-d1bac2d3-b6e7-411a-a2e9-28f82d5dfbad.png)

[03:42:00 ERROR]: #!#!
[03:42:00 ERROR]: #!#! [Skript] Severe Error:
[03:42:00 ERROR]: #!#!
[03:42:00 ERROR]: #!#! Something went horribly wrong with Skript.
[03:42:00 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[03:42:00 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[03:42:00 ERROR]: #!#! Here is full list of them:
[03:42:00 ERROR]: #!#! skript-yaml v1.4 skUtilities v0.9.2 (https://tim740.github.io/) DiSky v3.7.0 (https://disky.itsthesky.info/) FunnySkAddon v2.2.17-Beta (funnyskaddon.pl) skript-db v1.3.3
[03:42:00 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[03:42:00 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[03:42:00 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[03:42:00 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[03:42:00 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[03:42:00 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[03:42:00 ERROR]: #!#!
[03:42:00 ERROR]: #!#! Stack trace:
[03:42:00 ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[03:42:00 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:272)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getSingle(UnparsedLiteral.java:302)
[03:42:00 ERROR]: #!#!     at pl.funnyskaddon.skript.EventExtensionKt.getGuild(EventExtension.kt:48)
[03:42:00 ERROR]: #!#!     at pl.funnyskaddon.skript.EventExtensionKt.getGuildOption(EventExtension.kt:52)
[03:42:00 ERROR]: #!#!     at pl.funnyskaddon.skript.expression.guild.GuildMembersExpression.get(GuildMembersExpression.kt:38)
[03:42:00 ERROR]: #!#!     at pl.funnyskaddon.skript.expression.guild.GuildMembersExpression.get(GuildMembersExpression.kt:17)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:273)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:250)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:258)
[03:42:00 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175)
[03:42:00 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[03:42:00 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[03:42:00 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[03:42:00 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2177)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[03:42:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[03:42:00 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[03:42:00 ERROR]: #!#!
[03:42:00 ERROR]: #!#! Version Information:
[03:42:00 ERROR]: #!#!   Skript: 2.6.1 (latest)
[03:42:00 ERROR]: #!#!     Flavor: skriptlang-github
[03:42:00 ERROR]: #!#!     Date: 22:18:42.554713200
[03:42:00 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[03:42:00 ERROR]: #!#!   Minecraft: 1.16.5
[03:42:00 ERROR]: #!#!   Java: 16.0.2 (Java HotSpot(TM) 64-Bit Server VM 16.0.2+7-67)
[03:42:00 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[03:42:00 ERROR]: #!#!
[03:42:00 ERROR]: #!#! Server platform: Paper
[03:42:00 ERROR]: #!#!
[03:42:00 ERROR]: #!#! Current node: null
[03:42:00 ERROR]: #!#! Current item: set {_list::*} (as java.lang.Object) to null
[03:42:00 ERROR]: #!#! Current trigger: command /galert (simple event) (discord.sk, line 1)
[03:42:00 ERROR]: #!#!
[03:42:00 ERROR]: #!#! Thread: Server thread
[03:42:00 ERROR]: #!#!
[03:42:00 ERROR]: #!#! Language: english
[03:42:00 ERROR]: #!#! Link parse mode: DISABLED
[03:42:00 ERROR]: #!#!
[03:42:00 ERROR]: #!#! End of Error.
[03:42:00 ERROR]: #!#!

**Comment by P3ridot** [comment]
GH-36

**Comment by P3ridot** [comment]
Następne błędy z tym `UnparsedLiterals must be converted before use` zgłaszaj w GH-33
