### ISSUE TITLE
Fix UnparsedLiteral exception in conditions

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#50]
```
[17:00:14] [Server thread/ERROR]: #!#!
[17:00:14] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:00:14] [Server thread/ERROR]: #!#!
[17:00:14] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[17:00:14] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:00:14] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:00:14] [Server thread/ERROR]: #!#! Here is full list of them:
[17:00:14] [Server thread/ERROR]: #!#! skript-yaml v1.4 FunnySkAddon v2.2.20-Beta (funnyskaddon.pl) skript-db v1.3.3
[17:00:14] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:00:14] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:00:14] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:00:14] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:00:14] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:00:14] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:00:14] [Server thread/ERROR]: #!#!
[17:00:14] [Server thread/ERROR]: #!#! Stack trace:
[17:00:14] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[17:00:14] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:272)
[17:00:14] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.UnparsedLiteral.getSingle(UnparsedLiteral.java:302)
[17:00:14] [Server thread/ERROR]: #!#! at pl.funnyskaddon.skript.EventExtensionKt.getGuild(EventExtension.kt:47)
[17:00:14] [Server thread/ERROR]: #!#! at pl.funnyskaddon.skript.condition.guild.GuildDoesExistCondition.check(GuildDoesExistCondition.kt:31)
[17:00:14] [Server thread/ERROR]: #!#! at ch.njol.skript.sections.SecConditional.walk(SecConditional.java:165)
[17:00:14] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[17:00:14] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[17:00:14] [Server thread/ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285)
[17:00:14] [Server thread/ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:250)
[17:00:14] [Server thread/ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
[17:00:14] [Server thread/ERROR]: #!#! at ch.njol.skript.command.Commands.handleCommand(Commands.java:258)
[17:00:14] [Server thread/ERROR]: #!#! at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175)
[17:00:14] [Server thread/ERROR]: #!#! at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
[17:00:14] [Server thread/ERROR]: #!#! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:00:14] [Server thread/ERROR]: #!#! at java.lang.reflect.Method.invoke(Method.java:498)
[17:00:14] [Server thread/ERROR]: #!#! at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[17:00:14] [Server thread/ERROR]: #!#! at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[17:00:14] [Server thread/ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:00:14] [Server thread/ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[17:00:14] [Server thread/ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[17:00:14] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1181)
[17:00:14] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[17:00:14] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:00:14] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:00:14] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:00:14] [Server thread/ERROR]: #!#! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:00:14] [Server thread/ERROR]: #!#! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:00:14] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:00:14] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[17:00:14] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[17:00:14] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[17:00:14] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[17:00:14] [Server thread/ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[17:00:14] [Server thread/ERROR]: #!#!
[17:00:14] [Server thread/ERROR]: #!#! Version Information:
[17:00:14] [Server thread/ERROR]: #!#! Skript: 2.6 (latest)
[17:00:14] [Server thread/ERROR]: #!#! Flavor: github-matocolotoe-1.8
[17:00:14] [Server thread/ERROR]: #!#! Date: 19:38:08.600770900
[17:00:14] [Server thread/ERROR]: #!#! Bukkit: 1.8.8-R0.1-SNAPSHOT
[17:00:14] [Server thread/ERROR]: #!#! Minecraft: 1.8.8
[17:00:14] [Server thread/ERROR]: #!#! Java: 1.8.0_242 (OpenJDK 64-Bit Server VM 25.242-b08)
[17:00:14] [Server thread/ERROR]: #!#! OS: Linux amd64 4.9.0-12-amd64
[17:00:14] [Server thread/ERROR]: #!#!
[17:00:14] [Server thread/ERROR]: #!#! Server platform: Paper
[17:00:14] [Server thread/ERROR]: #!#!
[17:00:14] [Server thread/ERROR]: #!#! Current node: null
[17:00:14] [Server thread/ERROR]: #!#! Current item: if funny condition
[17:00:14] [Server thread/ERROR]: #!#! Current trigger: command /info (simple event) (core.sk, line 151)
[17:00:14] [Server thread/ERROR]: #!#!
[17:00:14] [Server thread/ERROR]: #!#! Thread: Server thread
[17:00:14] [Server thread/ERROR]: #!#!
[17:00:14] [Server thread/ERROR]: #!#! Language: english
[17:00:14] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[17:00:14] [Server thread/ERROR]: #!#!
[17:00:14] [Server thread/ERROR]: #!#! End of Error.
[17:00:14] [Server thread/ERROR]: #!#!
```

![image](https://user-images.githubusercontent.com/83598982/154808547-e0010be2-c3e7-4076-a6e8-246a4f88955e.png)

**Comment by P3ridot** [comment]
Na [2.2.21-Beta](https://github.com/FunnyGuilds/FunnySkAddon/releases/tag/2.2.21-Beta) powinno już wszystko działać
