### ISSUE TITLE
get endercrystal location

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#52]
![image](https://user-images.githubusercontent.com/83598982/158035581-32592a43-df81-46db-a88b-b7734a5725bd.png)

`[22:26:19 ERROR]: Could not pass event GuildCreateEvent to Skript v2.6
java.lang.NoSuchMethodError: 'java.lang.Object panda.std.Option.orNull()'
        at pl.funnyskaddon.skript.expression.guild.GuildEndercrystalLocationExpression.get(GuildEndercrystalLocationExpression.kt:44) ~[?:?]
        at pl.funnyskaddon.skript.expression.guild.GuildEndercrystalLocationExpression.get(GuildEndercrystalLocationExpression.kt:15) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99) ~[?:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:273) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[?:?]
        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-792]
        at net.dzikoysk.funnyguilds.event.SimpleEventHandler.handle(SimpleEventHandler.java:8) ~[?:?]
        at net.dzikoysk.funnyguilds.feature.command.user.CreateCommand.execute(CreateCommand.java:233) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.panda_lang.utilities.inject.MethodInjector.invoke(MethodInjector.java:45) ~[?:?]
        at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:228) ~[?:?]
        at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:112) ~[?:?]
        at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:84) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-792]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

[22:27:35 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[22:27:35 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[22:27:35 INFO]: [Skript] Server Version: git-Paper-792 (MC: 1.16.5)
[22:27:35 INFO]: [Skript] Skript Version: 2.6
[22:27:35 INFO]: [Skript] Installed Skript Addons:
[22:27:35 INFO]: [Skript]  - skript-ping v0.2
[22:27:35 INFO]: [Skript]  - FunnySkAddon v2.2.21-Beta (funnyskaddon.pl)
[22:27:35 INFO]: [Skript]  - Skellett v2.0.1 (https://forums.skunity.com/resources/skellett.24/)
[22:27:35 INFO]: [Skript]  - skript-yaml v1.4
[22:27:35 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[22:27:35 INFO]: [Skript]  - HolographicDisplaysAddon v1.0.0b
[22:27:35 INFO]: [Skript]  - skript-db v1.3.3
[22:27:35 INFO]: [Skript]  - SkBee v1.14.2 (https://github.com/ShaneBeee/SkBee)

**Comment by P3ridot** [comment]
Na [2.3.0](https://github.com/FunnyGuilds/FunnySkAddon/releases/tag/2.3.0) powinno działać
