### ISSUE TITLE
Is in guild region - UnparsedLiterals error

### ISSUE THREAD

**Issue by pawelkuwa** [FunnyGuilds/FunnySkAddon#54]
```
[18:29:57 ERROR]: #!#! [Skript] Severe Error:
[18:29:57 ERROR]: #!#!
[18:29:57 ERROR]: #!#! Something went horribly wrong with Skript.
[18:29:57 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:29:57 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[18:29:57 ERROR]: #!#! Here is full list of them:
[18:29:57 ERROR]: #!#! skRayFall v1.9.26 (https://sk.rayfall.net/) skript-yaml v1.4 FunnySkAddon v2.3.0 (funnyskaddon.pl)
[18:29:57 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[18:29:57 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[18:29:57 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[18:29:57 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[18:29:57 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[18:29:57 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[18:29:57 ERROR]: #!#!
[18:29:57 ERROR]: #!#! Stack trace:
[18:29:57 ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[18:29:57 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:272)
[18:29:57 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getSingle(UnparsedLiteral.java:302)
[18:29:57 ERROR]: #!#!     at pl.funnyskaddon.skript.EventExtensionKt.getGuild(EventExtension.kt:47)
[18:29:57 ERROR]: #!#!     at pl.funnyskaddon.skript.condition.guild.GuildIsLocationInRegion.check(GuildIsLocationInRegion.kt:45)
[18:29:57 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:55)
[18:29:57 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:50)
[18:29:57 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[18:29:57 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[18:29:57 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153)
[18:29:57 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111)
[18:29:57 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[18:29:57 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:29:57 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[18:29:57 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[18:29:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
[18:29:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463)
[18:29:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763)
[18:29:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
[18:29:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[18:29:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:29:57 ERROR]: #!#!     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[18:29:57 ERROR]: #!#!     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[18:29:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[18:29:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[18:29:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[18:29:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[18:29:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[18:29:57 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[18:29:57 ERROR]: #!#!
[18:29:57 ERROR]: #!#! Version Information:
[18:29:57 ERROR]: #!#!   Skript: 2.5.3 (OUTDATED)
[18:29:57 ERROR]: #!#!     Flavor: github-matocolotoe-1.8
[18:29:57 ERROR]: #!#!     Date: 2020-12-22
[18:29:57 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[18:29:57 ERROR]: #!#!   Minecraft: 1.8.8
[18:29:57 ERROR]: #!#!   Java: 17.0.2 (Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86)
[18:29:57 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[18:29:57 ERROR]: #!#!
[18:29:57 ERROR]: #!#! Server platform: Paper
[18:29:57 ERROR]: #!#!
[18:29:57 ERROR]: #!#! Current node: null
[18:29:57 ERROR]: #!#! Current item: funny condition
[18:29:57 ERROR]: #!#! Current trigger: right click on chest or trapped chest (rightclick on ([[itemtype:chest]] or [[itemtype:trapped chest]])[class ch.njol.skript.aliases.ItemType]) (core1.sk, line 539)
[18:29:57 ERROR]: #!#!
[18:29:57 ERROR]: #!#! Thread: Server thread
[18:29:57 ERROR]: #!#!
[18:29:57 ERROR]: #!#! Language: english
[18:29:57 ERROR]: #!#! Link parse mode: DISABLED
[18:29:57 ERROR]: #!#!
[18:29:57 ERROR]: #!#! End of Error.
[18:29:57 ERROR]: #!#!

[18:30:51 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases

[18:30:51 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript

[18:30:51 INFO]: [Skript] Server Version: git-PaperSpigot-"4c7641d" (MC: 1.8.8)

[18:30:51 INFO]: [Skript] Skript Version: 2.5.3

[18:30:51 INFO]: [Skript] Installed Skript Addons:

[18:30:51 INFO]: [Skript]  - FunnySkAddon v2.3.0 (funnyskaddon.pl)

[18:30:51 INFO]: [Skript]  - skript-yaml v1.4

[18:30:51 INFO]: [Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
```

Kod:
```
on right click on chest or trapped chest:
    if location of event-block is in guild player's guild region:
        broadcast "test"
 ```

**Comment by P3ridot** [comment]
Zamień
`if location of event-block is in guild player's guild region`
na
`if location of event-block is in player's guild region`
Powinno zadziałać
